package chimahon.custom.youtube

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.util.Locale

class YouTubeStreamSelectionTest {

    private fun stream(
        itag: Int,
        bitrate: Int,
        format: MediaFormat = MediaFormat.WEBMA_OPUS,
        trackId: String? = null,
        trackName: String? = null,
        type: AudioTrackType? = null,
        locale: Locale? = null,
        isUrl: Boolean = true,
    ): AudioStream = AudioStream.Builder()
        .setId("$itag-${trackId ?: "x"}")
        .setContent("https://example.invalid/$itag/${trackId ?: "x"}", isUrl)
        .setMediaFormat(format)
        .setAverageBitrate(bitrate)
        .setAudioTrackId(trackId)
        .setAudioTrackName(trackName)
        .setAudioTrackType(type)
        .setAudioLocale(locale)
        .build()

    @Test
    fun singleLanguageVideoYieldsOneM4aTrackNamedAudio() {
        val tracks = YouTubeStreamSelection.audioTracks(
            listOf(
                stream(139, 48, MediaFormat.M4A),
                stream(140, 128, MediaFormat.M4A),
                stream(249, 50),
                stream(250, 70),
                stream(251, 160),
            ),
        )

        assertEquals(1, tracks.size)
        assertEquals("https://example.invalid/140/x", tracks.single().url)
        assertEquals("Audio", tracks.single().lang)
    }

    @Test
    fun dubbedVideoYieldsOriginalFirstThenDubWithMarker() {
        val tracks = YouTubeStreamSelection.audioTracks(
            listOf(
                stream(139, 48, MediaFormat.M4A, "en-US.10", "English (US)", AudioTrackType.DUBBED, Locale.US),
                stream(139, 48, MediaFormat.M4A, "fr-FR.4", "French (FR) original", AudioTrackType.ORIGINAL, Locale.FRANCE),
                stream(251, 160, trackId = "en-US.10", trackName = "English (US)", type = AudioTrackType.DUBBED, locale = Locale.US),
                stream(140, 128, MediaFormat.M4A, "fr-FR.4", "French (FR) original", AudioTrackType.ORIGINAL, Locale.FRANCE),
                stream(251, 160, trackId = "fr-FR.4", trackName = "French (FR) original", type = AudioTrackType.ORIGINAL, locale = Locale.FRANCE),
            ),
        )

        // The dub only has the 48 kbps HE-AAC M4A, which is below the floor, so Opus wins there.
        assertEquals(
            listOf(
                "French (FR) original" to "https://example.invalid/140/fr-FR.4",
                "English (US) (dubbed)" to "https://example.invalid/251/en-US.10",
            ),
            tracks.map { it.lang to it.url },
        )
    }

    @Test
    fun reliableAudioOffPicksBestBitrateRegardlessOfFormat() {
        val tracks = YouTubeStreamSelection.audioTracks(
            listOf(
                stream(140, 128, MediaFormat.M4A),
                stream(251, 160),
            ),
            preferReliableAudio = false,
        )

        assertEquals(listOf("https://example.invalid/251/x"), tracks.map { it.url })
    }

    @Test
    fun nonUrlStreamsAreSkipped() {
        val tracks = YouTubeStreamSelection.audioTracks(
            listOf(
                stream(251, 160, isUrl = false),
                stream(140, 128, MediaFormat.M4A),
            ),
        )

        assertEquals(listOf("https://example.invalid/140/x"), tracks.map { it.url })
    }

    private fun subtitle(languageCode: String, auto: Boolean): SubtitlesStream = SubtitlesStream.Builder()
        .setContent("https://example.invalid/sub/$languageCode/$auto", true)
        .setMediaFormat(MediaFormat.VTT)
        .setLanguageCode(languageCode)
        .setAutoGenerated(auto)
        .build()

    @Test
    fun manualSubtitlesComeFirstAndAutoGeneratedOnesAreLabelled() {
        val tracks = YouTubeStreamSelection.subtitleTracks(
            listOf(subtitle("en-US", auto = true), subtitle("fr", auto = true), subtitle("fr-CA", auto = false)),
        )

        assertEquals(
            listOf(
                "https://example.invalid/sub/fr-CA/false",
                "https://example.invalid/sub/en-US/true",
                "https://example.invalid/sub/fr/true",
            ),
            tracks.map { it.url },
        )
        assertEquals(listOf(false, true, true), tracks.map { it.lang.endsWith(" (auto-generated)") })
    }
}
