package chimahon.custom.youtube

import eu.kanade.tachiyomi.animesource.model.Track
import org.schabi.newpipe.extractor.MediaFormat
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.AudioTrackType
import org.schabi.newpipe.extractor.stream.SubtitlesStream

/**
 * Which of the streams NewPipe returns are handed to the player, and in what order.
 *
 * Kept apart from `YouTubeResolver` so that a change on YouTube's side (a new audio track
 * type, a format that starts stalling, a different caption order) is a change to one rule
 * here and its test, not to the fetching code. Everything is a pure function of NewPipe's
 * stream model.
 */
internal object YouTubeStreamSelection {

    /** Sits between YouTube's 48 kbps HE-AAC tier and its 128 kbps AAC tier. */
    private const val RELIABLE_AUDIO_MIN_BITRATE = 96

    /**
     * Manually written captions first, auto-generated ones after and labelled. The player
     * selects the first track whose title matches the preferred language, and YouTube lists
     * its speech-recognition captions ahead of the uploader's own.
     */
    fun subtitleTracks(subtitles: List<SubtitlesStream>): List<Track> =
        subtitles
            .filter { it.content.isNotBlank() }
            .sortedBy { it.isAutoGenerated }
            .map { sub ->
                val name = sub.displayLanguageName
                    ?: sub.languageTag
                    ?: sub.locale?.displayLanguage
                    ?: ""
                Track(
                    url = sub.content,
                    lang = if (sub.isAutoGenerated) "$name (auto-generated)" else name,
                )
            }
            .distinctBy { it.url to it.lang }

    /**
     * One stream per audio track (language), the original first. The player attaches every
     * entry as a blocking external `audio-add`, so handing back all five itags of every
     * language delayed audio by seconds on dubbed videos.
     *
     * With [preferReliableAudio], M4A wins over Opus/WebM as long as it is not the 48 kbps
     * HE-AAC tier: resuming mid-video seeks the external audio, and on a throttled connection
     * mpv's Matroska demuxer took close to a minute to reach the target (57 s on the user's
     * phone) while the MP4 demuxer lands on the fragment directly (0.6 s, same video).
     */
    fun audioTracks(streams: List<AudioStream>, preferReliableAudio: Boolean = true): List<Track> =
        streams
            .filter { it.content.isNotBlank() && it.isUrl }
            .groupBy { it.audioTrackId }
            .values
            .map { group ->
                group.maxWith(
                    compareBy<AudioStream> {
                        preferReliableAudio && it.format == MediaFormat.M4A && it.averageBitrate >= RELIABLE_AUDIO_MIN_BITRATE
                    }.thenBy { it.averageBitrate },
                )
            }
            .sortedWith(
                compareBy<AudioStream> { it.audioTrackType != null && it.audioTrackType != AudioTrackType.ORIGINAL }
                    .thenByDescending { it.averageBitrate },
            )
            .map { audio ->
                val name = audio.audioTrackName
                    ?: audio.audioLocale?.displayLanguage?.takeIf { it.isNotBlank() }
                    ?: "Audio"
                Track(
                    url = audio.content,
                    lang = if (audio.audioTrackType == AudioTrackType.DUBBED) "$name (dubbed)" else name,
                )
            }
}
